import { Champion, DraftPhase, DraftSlot } from './types';

// Helper to get image URLs compatible with Data Dragon
export const getChampionAssets = (championId: string) => {
  return {
    loading: `https://ddragon.leagueoflegends.com/cdn/img/champion/loading/${championId}_0.jpg`,
    square: `https://ddragon.leagueoflegends.com/cdn/14.2.1/img/champion/${championId}.png`
  };
};

// IDs match Data Dragon format
export const ALL_CHAMPIONS: Champion[] = [
  { id: 'Aatrox', name: 'Aatrox', roles: ['Top'], tags: ['Teamfight', 'Sustain'], counters: ['Sion', 'ChoGath', 'Mundo'] },
  { id: 'Ahri', name: 'Ahri', roles: ['Mid'], tags: ['Mobility', 'Pick'], counters: ['Xerath', 'Lux', 'Viktor'] },
  { id: 'Alistar', name: 'Alistar', roles: ['Support'], tags: ['Engage', 'Tank'], counters: ['Leona', 'Blitzcrank', 'Nautilus'] },
  { id: 'Amumu', name: 'Amumu', roles: ['Jungle', 'Support'], tags: ['Teamfight', 'Engage'], counters: ['MasterYi', 'Graves'] },
  { id: 'Ashe', name: 'Ashe', roles: ['Bot', 'Support'], tags: ['Utility', 'Engage'], counters: ['Kalista', 'Vayne', 'Zeri'] },
  { id: 'Azir', name: 'Azir', roles: ['Mid'], tags: ['Scaling', 'Teamfight', 'Control'], counters: ['Corki', 'Orianna', 'Heimerdinger'] },
  { id: 'Blitzcrank', name: 'Blitzcrank', roles: ['Support'], tags: ['Pick', 'Engage'], counters: ['Soraka', 'Sona', 'Senna'] },
  { id: 'Caitlyn', name: 'Caitlyn', roles: ['Bot'], tags: ['EarlyGame', 'Poke', 'Siege'], counters: ['Vayne', 'Twitch', 'Draven'] },
  { id: 'Camille', name: 'Camille', roles: ['Top', 'Support'], tags: ['SplitPush', 'Pick'], counters: ['Aatrox', 'Gnar', 'Riven'] },
  { id: 'Darius', name: 'Darius', roles: ['Top'], tags: ['EarlyGame', 'Snowball'], counters: ['Sion', 'Nasus', 'Yasuo', 'Garen'] },
  { id: 'Draven', name: 'Draven', roles: ['Bot'], tags: ['EarlyGame', 'Snowball'], counters: ['Kaisa', 'Vayne', 'Ezreal', 'Zeri'] },
  { id: 'DrMundo', name: 'Dr. Mundo', roles: ['Top', 'Jungle'], tags: ['Tank', 'Sustain'], counters: ['Teemo', 'Singed', 'Maokai'] },
  { id: 'Ezreal', name: 'Ezreal', roles: ['Bot'], tags: ['Poke', 'Safe'], counters: ['Blitzcrank', 'Ashe', 'Nautilus'] },
  { id: 'Fiora', name: 'Fiora', roles: ['Top'], tags: ['SplitPush', 'Duelist', 'Scaling'], counters: ['Aatrox', 'Kled', 'Ornn', 'Sion'] },
  { id: 'Gragas', name: 'Gragas', roles: ['Top', 'Jungle', 'Mid'], tags: ['Disengage', 'Burst'], counters: ['Jax', 'Riven', 'Akali'] },
  { id: 'Janna', name: 'Janna', roles: ['Support'], tags: ['Disengage', 'Enchanter'], counters: ['Leona', 'Rell', 'Alistar', 'Zac'] },
  { id: 'JarvanIV', name: 'Jarvan IV', roles: ['Jungle'], tags: ['Engage', 'EarlyGame'], counters: ['Olaf', 'Skarner'] },
  { id: 'Jax', name: 'Jax', roles: ['Top', 'Jungle'], tags: ['Scaling', 'SplitPush', 'Duelist'], counters: ['Irelia', 'Camille', 'TwistedFate', 'Yone'] },
  { id: 'Jhin', name: 'Jhin', roles: ['Bot'], tags: ['Utility', 'Burst'], counters: ['Draven', 'MissFortune'] },
  { id: 'Jinx', name: 'Jinx', roles: ['Bot'], tags: ['Scaling', 'Teamfight'], counters: ['Caitlyn', 'Aphelios'] },
  { id: 'Kaisa', name: 'Kai\'Sa', roles: ['Bot'], tags: ['Scaling', 'Assassin'], counters: ['Ezreal', 'Jhin'] },
  { id: 'Karma', name: 'Karma', roles: ['Support', 'Mid'], tags: ['Poke', 'EarlyGame'], counters: ['Alistar', 'Braum'] },
  { id: 'Karthus', name: 'Karthus', roles: ['Jungle', 'Bot'], tags: ['Scaling', 'Teamfight'], counters: ['Graves', 'Kindred'] },
  { id: 'LeeSin', name: 'Lee Sin', roles: ['Jungle'], tags: ['EarlyGame', 'Playmaker'], counters: ['Evelynn', 'Karthus', 'Amumu'] },
  { id: 'Leona', name: 'Leona', roles: ['Support'], tags: ['Engage', 'Tank'], counters: ['Nautilus', 'Yuumi', 'Sona'] },
  { id: 'Lucian', name: 'Lucian', roles: ['Bot', 'Mid'], tags: ['EarlyGame', 'Burst'], counters: ['Kassadin', 'Corki', 'Azir'] },
  { id: 'Lulu', name: 'Lulu', roles: ['Support'], tags: ['Peel', 'Enchanter'], counters: ['Zed', 'Katarina', 'Leona', 'Rengar'] },
  { id: 'Lux', name: 'Lux', roles: ['Support', 'Mid'], tags: ['Poke', 'Burst'], counters: ['Zoe', 'Malzahar'] },
  { id: 'Malphite', name: 'Malphite', roles: ['Top', 'Mid'], tags: ['Engage', 'Teamfight', 'Tank'], counters: ['Jayce', 'Quinn', 'Vayne', 'Yasuo', 'Yone', 'Zeri'] },
  { id: 'Maokai', name: 'Maokai', roles: ['Top', 'Jungle', 'Support'], tags: ['Engage', 'Control'], counters: ['Leblanc', 'Akali'] },
  { id: 'MissFortune', name: 'Miss Fortune', roles: ['Bot'], tags: ['Teamfight', 'Bully'], counters: ['Zyra', 'Heimerdinger'] },
  { id: 'Nautilus', name: 'Nautilus', roles: ['Support'], tags: ['Engage', 'Tank'], counters: ['Blitzcrank', 'Pyke'] },
  { id: 'Orianna', name: 'Orianna', roles: ['Mid'], tags: ['Control', 'Teamfight'], counters: ['Azir', 'Ryze'] },
  { id: 'Ornn', name: 'Ornn', roles: ['Top'], tags: ['Tank', 'Engage', 'Scaling'], counters: ['Jayce', 'Kennen'] },
  { id: 'Rakan', name: 'Rakan', roles: ['Support'], tags: ['Engage', 'Mobility'], counters: ['Xayah', 'Morgana'] },
  { id: 'Rell', name: 'Rell', roles: ['Support', 'Jungle'], tags: ['Engage', 'Tank'], counters: ['TahmKench', 'Sett'] },
  { id: 'Renekton', name: 'Renekton', roles: ['Top'], tags: ['EarlyGame', 'Bully'], counters: ['Yasuo', 'Yone', 'Riven', 'Irelia'] },
  { id: 'Riven', name: 'Riven', roles: ['Top'], tags: ['Snowball', 'Duelist'], counters: ['Yasuo', 'Yone', 'Aatrox'] },
  { id: 'Sejuani', name: 'Sejuani', roles: ['Jungle', 'Top'], tags: ['Tank', 'Engage'], counters: ['Belveth', 'Graves'] },
  { id: 'Senna', name: 'Senna', roles: ['Support', 'Bot'], tags: ['Scaling', 'Poke'], counters: ['Galio', 'Sett'] },
  { id: 'Sett', name: 'Sett', roles: ['Top', 'Support'], tags: ['Teamfight', 'Tank'], counters: ['Kassadin', 'Irelia'] },
  { id: 'Sion', name: 'Sion', roles: ['Top'], tags: ['Tank', 'Scaling'], counters: ['Malphite', 'Teemo'] },
  { id: 'Sylas', name: 'Sylas', roles: ['Mid', 'Top'], tags: ['Skirmish', 'Heal'], counters: ['Malphite', 'Alister', 'TwistedFate'] },
  { id: 'Syndra', name: 'Syndra', roles: ['Mid'], tags: ['Control', 'Burst'], counters: ['Azir', 'Heimerdinger'] },
  { id: 'Thresh', name: 'Thresh', roles: ['Support'], tags: ['Pick', 'Control'], counters: ['Leona', 'Nautilus'] },
  { id: 'Tristana', name: 'Tristana', roles: ['Bot', 'Mid'], tags: ['Scaling', 'Push'], counters: ['Ezreal', 'Zeri'] },
  { id: 'TwistedFate', name: 'Twisted Fate', roles: ['Mid', 'Top'], tags: ['Global', 'Control'], counters: ['Akali', 'Kassadin'] },
  { id: 'Varus', name: 'Varus', roles: ['Bot', 'Mid'], tags: ['Poke', 'Teamfight'], counters: ['Caitlyn', 'Draven'] },
  { id: 'Vayne', name: 'Vayne', roles: ['Bot', 'Top'], tags: ['Scaling', 'TankBuster'], counters: ['Sion', 'Mundo', 'Ornn', 'ChoGath', 'Sejuani'] },
  { id: 'Vi', name: 'Vi', roles: ['Jungle'], tags: ['Engage', 'Pick'], counters: ['Zeri', 'Ezreal'] },
  { id: 'Viego', name: 'Viego', roles: ['Jungle'], tags: ['Skirmish', 'Reset'], counters: ['LeeSin', 'XinZhao'] },
  { id: 'Viktor', name: 'Viktor', roles: ['Mid'], tags: ['Control', 'Scaling'], counters: ['Sylas', 'Akali'] },
  { id: 'Xayah', name: 'Xayah', roles: ['Bot'], tags: ['Safety', 'Teamfight'], counters: ['Kaisa', 'Tristana', 'Samira'] },
  { id: 'Yasuo', name: 'Yasuo', roles: ['Mid', 'Top'], tags: ['Skirmish', 'Scaling'], counters: ['Lux', 'Ahri', 'Velkoz', 'TwistedFate'] },
  { id: 'Yone', name: 'Yone', roles: ['Mid', 'Top'], tags: ['Skirmish', 'Scaling'], counters: ['Zoe', 'AurelionSol', 'Azir'] },
  { id: 'Zed', name: 'Zed', roles: ['Mid'], tags: ['Assassin', 'Snowball'], counters: ['Veigar', 'Kassadin', 'Orianna'] },
  { id: 'Zeri', name: 'Zeri', roles: ['Bot'], tags: ['Scaling', 'Mobility'], counters: ['Ashe', 'Varus'] },
];

export const getInitialDraftSlots = (): DraftSlot[] => [
  { phase: DraftPhase.BLUE_BAN_1, team: 'blue', type: 'ban', champion: null, isActive: true },
  { phase: DraftPhase.RED_BAN_1, team: 'red', type: 'ban', champion: null, isActive: false },
  { phase: DraftPhase.BLUE_BAN_2, team: 'blue', type: 'ban', champion: null, isActive: false },
  { phase: DraftPhase.RED_BAN_2, team: 'red', type: 'ban', champion: null, isActive: false },
  { phase: DraftPhase.BLUE_BAN_3, team: 'blue', type: 'ban', champion: null, isActive: false },
  { phase: DraftPhase.RED_BAN_3, team: 'red', type: 'ban', champion: null, isActive: false },
  { phase: DraftPhase.BLUE_PICK_1, team: 'blue', type: 'pick', champion: null, isActive: false },
  { phase: DraftPhase.RED_PICK_1, team: 'red', type: 'pick', champion: null, isActive: false },
  { phase: DraftPhase.RED_PICK_2, team: 'red', type: 'pick', champion: null, isActive: false },
  { phase: DraftPhase.BLUE_PICK_2, team: 'blue', type: 'pick', champion: null, isActive: false },
  { phase: DraftPhase.BLUE_PICK_3, team: 'blue', type: 'pick', champion: null, isActive: false },
  { phase: DraftPhase.RED_PICK_3, team: 'red', type: 'pick', champion: null, isActive: false },
  { phase: DraftPhase.RED_BAN_4, team: 'red', type: 'ban', champion: null, isActive: false },
  { phase: DraftPhase.BLUE_BAN_4, team: 'blue', type: 'ban', champion: null, isActive: false },
  { phase: DraftPhase.RED_BAN_5, team: 'red', type: 'ban', champion: null, isActive: false },
  { phase: DraftPhase.BLUE_BAN_5, team: 'blue', type: 'ban', champion: null, isActive: false },
  { phase: DraftPhase.RED_PICK_4, team: 'red', type: 'pick', champion: null, isActive: false },
  { phase: DraftPhase.BLUE_PICK_4, team: 'blue', type: 'pick', champion: null, isActive: false },
  { phase: DraftPhase.BLUE_PICK_5, team: 'blue', type: 'pick', champion: null, isActive: false },
  { phase: DraftPhase.RED_PICK_5, team: 'red', type: 'pick', champion: null, isActive: false },
];